packages:
  - apps/*
  - packages/*

catalog:
  '@sinclair/typebox': 0.34.52
  '@types/node': 24.13.3
  typescript: 5.9.3
  vitest: 4.1.10

engineStrict: true
enableGlobalVirtualStore: false
nodeVersion: 24.11.1
savePrefix: ''

allowBuilds:
  esbuild: true
  sharp: true
