[package]
name = "droneworks-dji-parser-cli"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "droneworks-dji-parser-cli"
path = "src/main.rs"

[dependencies]
dji-log-parser = { path = "../dji-log-parser" }
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
